// APP
export const FETCH_APP_STARTED = 'FETCH_APP_STARTED';
export const FETCH_APP_SUCCEEDED = 'FETCH_APP_SUCCEEDED';
export const FETCH_APP_FAILED = 'FETCH_APP_FAILED';


// TRAILS
export const FETCH_TRAILS_STARTED = 'FETCH_TRAILS_STARTED';
export const FETCH_TRAILS_SUCCEEDED = 'FETCH_TRAILS_SUCCEEDED';
export const FETCH_TRAILS_FAILED = 'FETCH_TRAILS_FAILED';
export const TRAILS_CHANGE = 'TRAILS_CHANGE';
